services:
  app:
    build: .
    container_name: python_app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # İsteğe bağlı: Uygulamanızın çalışması için gerekli portları açın
    # ports:
    #   - "8000:8000"
    # İsteğe bağlı: Diğer servisler (örneğin, veritabanı) ekleyebilirsiniz
